/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.7.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDial>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QVBoxLayout>
#include <QtWidgets/QWidget>
#include "../../qcustomplot.h"

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *actionAbout;
    QAction *actionAboutQt;
    QAction *actionConnect;
    QAction *actionDisconnect;
    QAction *actionConfigure;
    QAction *actionClear;
    QAction *actionQuit;
    QWidget *centralWidget;
    QVBoxLayout *verticalLayout;
    QTabWidget *tabWidget;
    QWidget *tabTerminal;
    QWidget *tabMeasurement;
    QGroupBox *groupBoxPhase2_3;
    QLabel *label_45;
    QLabel *voltage_label_lt;
    QLabel *label_46;
    QLabel *label_47;
    QLabel *label_48;
    QLabel *current_label_lt;
    QLabel *label_49;
    QLabel *label_50;
    QLabel *power_label_lt;
    QLabel *label_51;
    QLabel *label_52;
    QLabel *apparent_label_lt;
    QLabel *label_53;
    QLabel *label_54;
    QLabel *reactive_label_lt;
    QLabel *powerfactor_label_lt;
    QLabel *label_57;
    QLabel *label_58;
    QLabel *temperature_label;
    QLabel *label_56;
    QLabel *label_59;
    QLabel *frequency_label;
    QLabel *label_20;
    QGroupBox *groupBoxPhase2;
    QLabel *label_23;
    QLabel *voltage_label_l2;
    QLabel *label_24;
    QLabel *label_25;
    QLabel *label_26;
    QLabel *current_label_l2;
    QLabel *label_27;
    QLabel *label_28;
    QLabel *power_label_l2;
    QLabel *label_29;
    QLabel *label_30;
    QLabel *apparent_label_l2;
    QLabel *label_31;
    QLabel *label_32;
    QLabel *reactive_label_l2;
    QLabel *powerfactor_label_l2;
    QLabel *energyCounterp_label_l2;
    QLabel *label_16;
    QLabel *label_15;
    QLabel *label_17;
    QLabel *cosinusPhi_label_l2;
    QLabel *label_33;
    QGroupBox *groupBoxPhase2_2;
    QLabel *label_34;
    QLabel *voltage_label_l3;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_37;
    QLabel *current_label_l3;
    QLabel *label_38;
    QLabel *label_39;
    QLabel *power_label_l3;
    QLabel *label_40;
    QLabel *label_41;
    QLabel *apparent_label_l3;
    QLabel *label_42;
    QLabel *label_43;
    QLabel *reactive_label_l3;
    QLabel *powerfactor_label_l3;
    QLabel *energyCounterp_label_l3;
    QLabel *label_18;
    QLabel *label_19;
    QLabel *label_21;
    QLabel *cosinusPhi_label_l3;
    QLabel *label_44;
    QGroupBox *groupBoxPhase1;
    QLabel *label;
    QLabel *voltage_label_l1;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *current_label_l1;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *power_label_l1;
    QLabel *label_7;
    QLabel *label_8;
    QLabel *apparent_label_l1;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *reactive_label_l1;
    QLabel *powerfactor_label_l1;
    QLabel *label_12;
    QLabel *energyCounterp_label_l1;
    QLabel *label_13;
    QLabel *label_14;
    QLabel *cosinusPhi_label_l1;
    QLabel *label_22;
    QLabel *label_11;
    QGroupBox *groupBox_2;
    QPushButton *pushButton;
    QPushButton *startSimmulation;
    QPushButton *bB_save_flash;
    QCheckBox *cbUseSimmulatedData;
    QComboBox *comboBox;
    QLabel *label_60;
    QLabel *label_63;
    QSpinBox *spinBoxAverage;
    QLabel *label_62;
    QLabel *period_label;
    QLabel *label_61;
    QPushButton *bB_clear_flash;
    QFrame *line;
    QFrame *line_2;
    QLabel *label_64;
    QPushButton *pB_CallibrateOffsetCurrent;
    QFrame *line_3;
    QComboBox *cBCalibrationSelection;
    QLabel *label_65;
    QDoubleSpinBox *dSBCalibrateValue;
    QLabel *labelCalibrateUnit;
    QPushButton *pBApplyCalibration;
    QWidget *tabAdvanced;
    QLabel *labelPaintPower;
    QLabel *cos_phi;
    QLabel *label_73;
    QCustomPlot *graphAdvanced;
    QGroupBox *groupBox;
    QWidget *tabScope;
    QCustomPlot *customPlot;
    QLineEdit *lineEditRefreshTime;
    QLabel *label_71;
    QLabel *label_72;
    QLabel *labelRefreshError;
    QComboBox *comboBoxScope;
    QCheckBox *radioButtonL1;
    QCheckBox *radioButtonL2;
    QCheckBox *radioButtonL3;
    QDial *scopeZoom;
    QLabel *label_74;
    QLabel *scopeZoomLabel;
    QLabel *label_75;
    QWidget *tabDatalogger;
    QTableWidget *tableWidgetData;
    QPushButton *pBAddDataloggerContent;
    QComboBox *cBDataloggerList;
    QPushButton *pBSaveDataloggerToPath;
    QPushButton *pBDeleteDataloggerContent;
    QRadioButton *rBEnableDatalogger;
    QSpinBox *sBDataloggerTime;
    QMenuBar *menuBar;
    QMenu *menuCalls;
    QMenu *menuTools;
    QMenu *menuHelp;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(760, 533);
        actionAbout = new QAction(MainWindow);
        actionAbout->setObjectName(QStringLiteral("actionAbout"));
        actionAboutQt = new QAction(MainWindow);
        actionAboutQt->setObjectName(QStringLiteral("actionAboutQt"));
        actionConnect = new QAction(MainWindow);
        actionConnect->setObjectName(QStringLiteral("actionConnect"));
        QIcon icon;
        icon.addFile(QStringLiteral(":/images/connect.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionConnect->setIcon(icon);
        actionDisconnect = new QAction(MainWindow);
        actionDisconnect->setObjectName(QStringLiteral("actionDisconnect"));
        QIcon icon1;
        icon1.addFile(QStringLiteral(":/images/disconnect.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionDisconnect->setIcon(icon1);
        actionConfigure = new QAction(MainWindow);
        actionConfigure->setObjectName(QStringLiteral("actionConfigure"));
        QIcon icon2;
        icon2.addFile(QStringLiteral(":/images/settings.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionConfigure->setIcon(icon2);
        actionClear = new QAction(MainWindow);
        actionClear->setObjectName(QStringLiteral("actionClear"));
        QIcon icon3;
        icon3.addFile(QStringLiteral(":/images/clear.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionClear->setIcon(icon3);
        actionQuit = new QAction(MainWindow);
        actionQuit->setObjectName(QStringLiteral("actionQuit"));
        QIcon icon4;
        icon4.addFile(QStringLiteral(":/images/application-exit.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionQuit->setIcon(icon4);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        verticalLayout = new QVBoxLayout(centralWidget);
        verticalLayout->setSpacing(6);
        verticalLayout->setContentsMargins(11, 11, 11, 11);
        verticalLayout->setObjectName(QStringLiteral("verticalLayout"));
        tabWidget = new QTabWidget(centralWidget);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        QPalette palette;
        QBrush brush(QColor(0, 0, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(255, 255, 255, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette.setBrush(QPalette::Active, QPalette::Light, brush1);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush1);
        QBrush brush2(QColor(127, 127, 127, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush2);
        QBrush brush3(QColor(170, 170, 170, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush3);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush1);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush1);
        QBrush brush4(QColor(255, 255, 220, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush4);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        tabWidget->setPalette(palette);
        tabTerminal = new QWidget();
        tabTerminal->setObjectName(QStringLiteral("tabTerminal"));
        tabWidget->addTab(tabTerminal, QString());
        tabMeasurement = new QWidget();
        tabMeasurement->setObjectName(QStringLiteral("tabMeasurement"));
        groupBoxPhase2_3 = new QGroupBox(tabMeasurement);
        groupBoxPhase2_3->setObjectName(QStringLiteral("groupBoxPhase2_3"));
        groupBoxPhase2_3->setGeometry(QRect(550, 0, 171, 211));
        QFont font;
        font.setPointSize(14);
        groupBoxPhase2_3->setFont(font);
        label_45 = new QLabel(groupBoxPhase2_3);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(10, 40, 20, 16));
        QFont font1;
        font1.setPointSize(16);
        label_45->setFont(font1);
        voltage_label_lt = new QLabel(groupBoxPhase2_3);
        voltage_label_lt->setObjectName(QStringLiteral("voltage_label_lt"));
        voltage_label_lt->setGeometry(QRect(40, 40, 61, 16));
        voltage_label_lt->setFont(font1);
        label_46 = new QLabel(groupBoxPhase2_3);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setGeometry(QRect(130, 40, 21, 16));
        label_46->setFont(font1);
        label_47 = new QLabel(groupBoxPhase2_3);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(130, 60, 21, 16));
        label_47->setFont(font1);
        label_48 = new QLabel(groupBoxPhase2_3);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(10, 60, 20, 16));
        label_48->setFont(font1);
        current_label_lt = new QLabel(groupBoxPhase2_3);
        current_label_lt->setObjectName(QStringLiteral("current_label_lt"));
        current_label_lt->setGeometry(QRect(40, 60, 61, 16));
        current_label_lt->setFont(font1);
        label_49 = new QLabel(groupBoxPhase2_3);
        label_49->setObjectName(QStringLiteral("label_49"));
        label_49->setGeometry(QRect(130, 80, 21, 16));
        label_49->setFont(font1);
        label_50 = new QLabel(groupBoxPhase2_3);
        label_50->setObjectName(QStringLiteral("label_50"));
        label_50->setGeometry(QRect(10, 80, 20, 16));
        label_50->setFont(font1);
        power_label_lt = new QLabel(groupBoxPhase2_3);
        power_label_lt->setObjectName(QStringLiteral("power_label_lt"));
        power_label_lt->setGeometry(QRect(40, 80, 61, 16));
        power_label_lt->setFont(font1);
        label_51 = new QLabel(groupBoxPhase2_3);
        label_51->setObjectName(QStringLiteral("label_51"));
        label_51->setGeometry(QRect(130, 100, 21, 16));
        label_51->setFont(font1);
        label_52 = new QLabel(groupBoxPhase2_3);
        label_52->setObjectName(QStringLiteral("label_52"));
        label_52->setGeometry(QRect(10, 100, 20, 16));
        label_52->setFont(font1);
        apparent_label_lt = new QLabel(groupBoxPhase2_3);
        apparent_label_lt->setObjectName(QStringLiteral("apparent_label_lt"));
        apparent_label_lt->setGeometry(QRect(40, 100, 61, 16));
        apparent_label_lt->setFont(font1);
        label_53 = new QLabel(groupBoxPhase2_3);
        label_53->setObjectName(QStringLiteral("label_53"));
        label_53->setGeometry(QRect(130, 120, 31, 16));
        label_53->setFont(font1);
        label_54 = new QLabel(groupBoxPhase2_3);
        label_54->setObjectName(QStringLiteral("label_54"));
        label_54->setGeometry(QRect(10, 120, 20, 16));
        label_54->setFont(font1);
        reactive_label_lt = new QLabel(groupBoxPhase2_3);
        reactive_label_lt->setObjectName(QStringLiteral("reactive_label_lt"));
        reactive_label_lt->setGeometry(QRect(40, 120, 61, 16));
        reactive_label_lt->setFont(font1);
        powerfactor_label_lt = new QLabel(groupBoxPhase2_3);
        powerfactor_label_lt->setObjectName(QStringLiteral("powerfactor_label_lt"));
        powerfactor_label_lt->setGeometry(QRect(40, 140, 61, 16));
        powerfactor_label_lt->setFont(font1);
        label_57 = new QLabel(groupBoxPhase2_3);
        label_57->setObjectName(QStringLiteral("label_57"));
        label_57->setGeometry(QRect(130, 190, 31, 16));
        label_57->setFont(font1);
        label_58 = new QLabel(groupBoxPhase2_3);
        label_58->setObjectName(QStringLiteral("label_58"));
        label_58->setGeometry(QRect(130, 170, 31, 16));
        label_58->setFont(font1);
        temperature_label = new QLabel(groupBoxPhase2_3);
        temperature_label->setObjectName(QStringLiteral("temperature_label"));
        temperature_label->setGeometry(QRect(50, 190, 61, 16));
        temperature_label->setFont(font1);
        label_56 = new QLabel(groupBoxPhase2_3);
        label_56->setObjectName(QStringLiteral("label_56"));
        label_56->setGeometry(QRect(10, 190, 31, 16));
        label_56->setFont(font1);
        label_59 = new QLabel(groupBoxPhase2_3);
        label_59->setObjectName(QStringLiteral("label_59"));
        label_59->setGeometry(QRect(10, 170, 31, 16));
        label_59->setFont(font1);
        frequency_label = new QLabel(groupBoxPhase2_3);
        frequency_label->setObjectName(QStringLiteral("frequency_label"));
        frequency_label->setGeometry(QRect(50, 170, 61, 16));
        frequency_label->setFont(font1);
        label_20 = new QLabel(groupBoxPhase2_3);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(10, 140, 31, 16));
        label_20->setFont(font1);
        groupBoxPhase2 = new QGroupBox(tabMeasurement);
        groupBoxPhase2->setObjectName(QStringLiteral("groupBoxPhase2"));
        groupBoxPhase2->setGeometry(QRect(190, 0, 171, 211));
        groupBoxPhase2->setFont(font);
        label_23 = new QLabel(groupBoxPhase2);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(10, 40, 20, 16));
        label_23->setFont(font1);
        voltage_label_l2 = new QLabel(groupBoxPhase2);
        voltage_label_l2->setObjectName(QStringLiteral("voltage_label_l2"));
        voltage_label_l2->setGeometry(QRect(40, 40, 81, 16));
        voltage_label_l2->setFont(font1);
        label_24 = new QLabel(groupBoxPhase2);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(130, 40, 21, 16));
        label_24->setFont(font1);
        label_25 = new QLabel(groupBoxPhase2);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(130, 60, 21, 16));
        label_25->setFont(font1);
        label_26 = new QLabel(groupBoxPhase2);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(10, 60, 20, 16));
        label_26->setFont(font1);
        current_label_l2 = new QLabel(groupBoxPhase2);
        current_label_l2->setObjectName(QStringLiteral("current_label_l2"));
        current_label_l2->setGeometry(QRect(40, 60, 81, 16));
        current_label_l2->setFont(font1);
        label_27 = new QLabel(groupBoxPhase2);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(130, 80, 21, 16));
        label_27->setFont(font1);
        label_28 = new QLabel(groupBoxPhase2);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(10, 80, 20, 16));
        label_28->setFont(font1);
        power_label_l2 = new QLabel(groupBoxPhase2);
        power_label_l2->setObjectName(QStringLiteral("power_label_l2"));
        power_label_l2->setGeometry(QRect(40, 80, 81, 16));
        power_label_l2->setFont(font1);
        label_29 = new QLabel(groupBoxPhase2);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(130, 100, 21, 16));
        label_29->setFont(font1);
        label_30 = new QLabel(groupBoxPhase2);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(10, 100, 20, 16));
        label_30->setFont(font1);
        apparent_label_l2 = new QLabel(groupBoxPhase2);
        apparent_label_l2->setObjectName(QStringLiteral("apparent_label_l2"));
        apparent_label_l2->setGeometry(QRect(40, 100, 81, 16));
        apparent_label_l2->setFont(font1);
        label_31 = new QLabel(groupBoxPhase2);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(130, 120, 31, 16));
        label_31->setFont(font1);
        label_32 = new QLabel(groupBoxPhase2);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(10, 120, 20, 16));
        label_32->setFont(font1);
        reactive_label_l2 = new QLabel(groupBoxPhase2);
        reactive_label_l2->setObjectName(QStringLiteral("reactive_label_l2"));
        reactive_label_l2->setGeometry(QRect(40, 120, 81, 16));
        reactive_label_l2->setFont(font1);
        powerfactor_label_l2 = new QLabel(groupBoxPhase2);
        powerfactor_label_l2->setObjectName(QStringLiteral("powerfactor_label_l2"));
        powerfactor_label_l2->setGeometry(QRect(40, 140, 81, 16));
        powerfactor_label_l2->setFont(font1);
        energyCounterp_label_l2 = new QLabel(groupBoxPhase2);
        energyCounterp_label_l2->setObjectName(QStringLiteral("energyCounterp_label_l2"));
        energyCounterp_label_l2->setGeometry(QRect(40, 180, 61, 16));
        energyCounterp_label_l2->setFont(font1);
        label_16 = new QLabel(groupBoxPhase2);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(10, 180, 31, 16));
        QFont font2;
        font2.setPointSize(18);
        label_16->setFont(font2);
        label_15 = new QLabel(groupBoxPhase2);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(10, 140, 31, 16));
        label_15->setFont(font1);
        label_17 = new QLabel(groupBoxPhase2);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(10, 160, 31, 16));
        label_17->setFont(font1);
        cosinusPhi_label_l2 = new QLabel(groupBoxPhase2);
        cosinusPhi_label_l2->setObjectName(QStringLiteral("cosinusPhi_label_l2"));
        cosinusPhi_label_l2->setGeometry(QRect(40, 160, 81, 16));
        cosinusPhi_label_l2->setFont(font1);
        label_33 = new QLabel(groupBoxPhase2);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(130, 160, 31, 16));
        label_33->setFont(font1);
        groupBoxPhase2_2 = new QGroupBox(tabMeasurement);
        groupBoxPhase2_2->setObjectName(QStringLiteral("groupBoxPhase2_2"));
        groupBoxPhase2_2->setEnabled(true);
        groupBoxPhase2_2->setGeometry(QRect(370, 0, 171, 211));
        groupBoxPhase2_2->setFont(font);
        label_34 = new QLabel(groupBoxPhase2_2);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(10, 40, 20, 16));
        label_34->setFont(font1);
        voltage_label_l3 = new QLabel(groupBoxPhase2_2);
        voltage_label_l3->setObjectName(QStringLiteral("voltage_label_l3"));
        voltage_label_l3->setGeometry(QRect(40, 40, 81, 16));
        voltage_label_l3->setFont(font1);
        label_35 = new QLabel(groupBoxPhase2_2);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(130, 40, 21, 16));
        label_35->setFont(font1);
        label_36 = new QLabel(groupBoxPhase2_2);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(130, 60, 21, 16));
        label_36->setFont(font1);
        label_37 = new QLabel(groupBoxPhase2_2);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(10, 60, 20, 16));
        label_37->setFont(font1);
        current_label_l3 = new QLabel(groupBoxPhase2_2);
        current_label_l3->setObjectName(QStringLiteral("current_label_l3"));
        current_label_l3->setGeometry(QRect(40, 60, 81, 16));
        current_label_l3->setFont(font1);
        label_38 = new QLabel(groupBoxPhase2_2);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(130, 80, 21, 16));
        label_38->setFont(font1);
        label_39 = new QLabel(groupBoxPhase2_2);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(10, 80, 20, 16));
        label_39->setFont(font1);
        power_label_l3 = new QLabel(groupBoxPhase2_2);
        power_label_l3->setObjectName(QStringLiteral("power_label_l3"));
        power_label_l3->setGeometry(QRect(40, 80, 81, 16));
        power_label_l3->setFont(font1);
        label_40 = new QLabel(groupBoxPhase2_2);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(130, 100, 21, 16));
        label_40->setFont(font1);
        label_41 = new QLabel(groupBoxPhase2_2);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(10, 100, 20, 16));
        label_41->setFont(font1);
        apparent_label_l3 = new QLabel(groupBoxPhase2_2);
        apparent_label_l3->setObjectName(QStringLiteral("apparent_label_l3"));
        apparent_label_l3->setGeometry(QRect(40, 100, 81, 16));
        apparent_label_l3->setFont(font1);
        label_42 = new QLabel(groupBoxPhase2_2);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(130, 120, 31, 16));
        label_42->setFont(font1);
        label_43 = new QLabel(groupBoxPhase2_2);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(10, 120, 20, 16));
        label_43->setFont(font1);
        reactive_label_l3 = new QLabel(groupBoxPhase2_2);
        reactive_label_l3->setObjectName(QStringLiteral("reactive_label_l3"));
        reactive_label_l3->setGeometry(QRect(40, 120, 81, 16));
        reactive_label_l3->setFont(font1);
        powerfactor_label_l3 = new QLabel(groupBoxPhase2_2);
        powerfactor_label_l3->setObjectName(QStringLiteral("powerfactor_label_l3"));
        powerfactor_label_l3->setGeometry(QRect(40, 140, 91, 16));
        powerfactor_label_l3->setFont(font1);
        energyCounterp_label_l3 = new QLabel(groupBoxPhase2_2);
        energyCounterp_label_l3->setObjectName(QStringLiteral("energyCounterp_label_l3"));
        energyCounterp_label_l3->setGeometry(QRect(40, 180, 61, 16));
        energyCounterp_label_l3->setFont(font1);
        label_18 = new QLabel(groupBoxPhase2_2);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(10, 180, 31, 16));
        label_18->setFont(font2);
        label_19 = new QLabel(groupBoxPhase2_2);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(10, 140, 31, 16));
        label_19->setFont(font1);
        label_21 = new QLabel(groupBoxPhase2_2);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(10, 160, 31, 16));
        label_21->setFont(font1);
        cosinusPhi_label_l3 = new QLabel(groupBoxPhase2_2);
        cosinusPhi_label_l3->setObjectName(QStringLiteral("cosinusPhi_label_l3"));
        cosinusPhi_label_l3->setGeometry(QRect(40, 160, 81, 16));
        cosinusPhi_label_l3->setFont(font1);
        label_44 = new QLabel(groupBoxPhase2_2);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(130, 160, 31, 16));
        label_44->setFont(font1);
        groupBoxPhase1 = new QGroupBox(tabMeasurement);
        groupBoxPhase1->setObjectName(QStringLiteral("groupBoxPhase1"));
        groupBoxPhase1->setGeometry(QRect(10, 0, 171, 211));
        groupBoxPhase1->setFont(font);
        label = new QLabel(groupBoxPhase1);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(10, 40, 20, 16));
        label->setFont(font1);
        voltage_label_l1 = new QLabel(groupBoxPhase1);
        voltage_label_l1->setObjectName(QStringLiteral("voltage_label_l1"));
        voltage_label_l1->setGeometry(QRect(50, 40, 81, 16));
        voltage_label_l1->setFont(font1);
        label_2 = new QLabel(groupBoxPhase1);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(140, 40, 21, 16));
        label_2->setFont(font1);
        label_3 = new QLabel(groupBoxPhase1);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(140, 60, 21, 16));
        label_3->setFont(font1);
        label_4 = new QLabel(groupBoxPhase1);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(10, 60, 20, 16));
        label_4->setFont(font1);
        current_label_l1 = new QLabel(groupBoxPhase1);
        current_label_l1->setObjectName(QStringLiteral("current_label_l1"));
        current_label_l1->setGeometry(QRect(50, 60, 81, 16));
        current_label_l1->setFont(font1);
        label_5 = new QLabel(groupBoxPhase1);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(140, 80, 21, 16));
        label_5->setFont(font1);
        label_6 = new QLabel(groupBoxPhase1);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(10, 80, 20, 16));
        label_6->setFont(font1);
        power_label_l1 = new QLabel(groupBoxPhase1);
        power_label_l1->setObjectName(QStringLiteral("power_label_l1"));
        power_label_l1->setGeometry(QRect(50, 80, 81, 16));
        power_label_l1->setFont(font1);
        label_7 = new QLabel(groupBoxPhase1);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(140, 100, 21, 16));
        label_7->setFont(font1);
        label_8 = new QLabel(groupBoxPhase1);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(10, 100, 20, 16));
        label_8->setFont(font1);
        apparent_label_l1 = new QLabel(groupBoxPhase1);
        apparent_label_l1->setObjectName(QStringLiteral("apparent_label_l1"));
        apparent_label_l1->setGeometry(QRect(50, 100, 81, 16));
        apparent_label_l1->setFont(font1);
        label_9 = new QLabel(groupBoxPhase1);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(140, 120, 31, 16));
        label_9->setFont(font1);
        label_10 = new QLabel(groupBoxPhase1);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(10, 120, 20, 16));
        label_10->setFont(font1);
        reactive_label_l1 = new QLabel(groupBoxPhase1);
        reactive_label_l1->setObjectName(QStringLiteral("reactive_label_l1"));
        reactive_label_l1->setGeometry(QRect(50, 120, 81, 16));
        reactive_label_l1->setFont(font1);
        powerfactor_label_l1 = new QLabel(groupBoxPhase1);
        powerfactor_label_l1->setObjectName(QStringLiteral("powerfactor_label_l1"));
        powerfactor_label_l1->setGeometry(QRect(50, 140, 81, 16));
        powerfactor_label_l1->setFont(font1);
        label_12 = new QLabel(groupBoxPhase1);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(10, 140, 31, 16));
        label_12->setFont(font1);
        energyCounterp_label_l1 = new QLabel(groupBoxPhase1);
        energyCounterp_label_l1->setObjectName(QStringLiteral("energyCounterp_label_l1"));
        energyCounterp_label_l1->setGeometry(QRect(50, 180, 81, 16));
        energyCounterp_label_l1->setFont(font1);
        label_13 = new QLabel(groupBoxPhase1);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(10, 180, 31, 16));
        label_13->setFont(font1);
        label_14 = new QLabel(groupBoxPhase1);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(10, 160, 31, 16));
        label_14->setFont(font1);
        cosinusPhi_label_l1 = new QLabel(groupBoxPhase1);
        cosinusPhi_label_l1->setObjectName(QStringLiteral("cosinusPhi_label_l1"));
        cosinusPhi_label_l1->setGeometry(QRect(50, 160, 81, 16));
        cosinusPhi_label_l1->setFont(font1);
        label_22 = new QLabel(groupBoxPhase1);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(140, 160, 31, 16));
        label_22->setFont(font1);
        label_11 = new QLabel(tabMeasurement);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(660, 410, 111, 16));
        groupBox_2 = new QGroupBox(tabMeasurement);
        groupBox_2->setObjectName(QStringLiteral("groupBox_2"));
        groupBox_2->setGeometry(QRect(10, 210, 711, 191));
        groupBox_2->setFont(font);
        pushButton = new QPushButton(groupBox_2);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(4, 30, 171, 32));
        startSimmulation = new QPushButton(groupBox_2);
        startSimmulation->setObjectName(QStringLiteral("startSimmulation"));
        startSimmulation->setGeometry(QRect(190, 30, 161, 32));
        bB_save_flash = new QPushButton(groupBox_2);
        bB_save_flash->setObjectName(QStringLiteral("bB_save_flash"));
        bB_save_flash->setGeometry(QRect(103, 56, 71, 32));
        cbUseSimmulatedData = new QCheckBox(groupBox_2);
        cbUseSimmulatedData->setObjectName(QStringLiteral("cbUseSimmulatedData"));
        cbUseSimmulatedData->setGeometry(QRect(200, 60, 161, 20));
        comboBox = new QComboBox(groupBox_2);
        comboBox->setObjectName(QStringLiteral("comboBox"));
        comboBox->setGeometry(QRect(550, 60, 151, 26));
        label_60 = new QLabel(groupBox_2);
        label_60->setObjectName(QStringLiteral("label_60"));
        label_60->setGeometry(QRect(580, 40, 121, 16));
        label_60->setFont(font1);
        label_63 = new QLabel(groupBox_2);
        label_63->setObjectName(QStringLiteral("label_63"));
        label_63->setGeometry(QRect(200, 105, 111, 16));
        label_63->setFont(font1);
        spinBoxAverage = new QSpinBox(groupBox_2);
        spinBoxAverage->setObjectName(QStringLiteral("spinBoxAverage"));
        spinBoxAverage->setGeometry(QRect(310, 100, 81, 24));
        spinBoxAverage->setMaximum(10000);
        spinBoxAverage->setValue(100);
        label_62 = new QLabel(groupBox_2);
        label_62->setObjectName(QStringLiteral("label_62"));
        label_62->setGeometry(QRect(320, 130, 81, 16));
        label_62->setFont(font1);
        period_label = new QLabel(groupBox_2);
        period_label->setObjectName(QStringLiteral("period_label"));
        period_label->setGeometry(QRect(260, 130, 61, 16));
        period_label->setFont(font1);
        label_61 = new QLabel(groupBox_2);
        label_61->setObjectName(QStringLiteral("label_61"));
        label_61->setGeometry(QRect(200, 130, 61, 16));
        label_61->setFont(font1);
        bB_clear_flash = new QPushButton(groupBox_2);
        bB_clear_flash->setObjectName(QStringLiteral("bB_clear_flash"));
        bB_clear_flash->setGeometry(QRect(50, 56, 61, 32));
        line = new QFrame(groupBox_2);
        line->setObjectName(QStringLiteral("line"));
        line->setGeometry(QRect(170, 40, 20, 141));
        line->setFrameShape(QFrame::VLine);
        line->setFrameShadow(QFrame::Sunken);
        line_2 = new QFrame(groupBox_2);
        line_2->setObjectName(QStringLiteral("line_2"));
        line_2->setGeometry(QRect(530, 40, 20, 121));
        line_2->setFrameShape(QFrame::VLine);
        line_2->setFrameShadow(QFrame::Sunken);
        label_64 = new QLabel(groupBox_2);
        label_64->setObjectName(QStringLiteral("label_64"));
        label_64->setGeometry(QRect(10, 61, 51, 16));
        label_64->setFont(font1);
        pB_CallibrateOffsetCurrent = new QPushButton(groupBox_2);
        pB_CallibrateOffsetCurrent->setObjectName(QStringLiteral("pB_CallibrateOffsetCurrent"));
        pB_CallibrateOffsetCurrent->setGeometry(QRect(3, 80, 171, 32));
        line_3 = new QFrame(groupBox_2);
        line_3->setObjectName(QStringLiteral("line_3"));
        line_3->setGeometry(QRect(10, 106, 151, 16));
        line_3->setFrameShape(QFrame::HLine);
        line_3->setFrameShadow(QFrame::Sunken);
        cBCalibrationSelection = new QComboBox(groupBox_2);
        cBCalibrationSelection->setObjectName(QStringLiteral("cBCalibrationSelection"));
        cBCalibrationSelection->setGeometry(QRect(70, 120, 101, 26));
        label_65 = new QLabel(groupBox_2);
        label_65->setObjectName(QStringLiteral("label_65"));
        label_65->setGeometry(QRect(10, 122, 81, 20));
        label_65->setFont(font1);
        dSBCalibrateValue = new QDoubleSpinBox(groupBox_2);
        dSBCalibrateValue->setObjectName(QStringLiteral("dSBCalibrateValue"));
        dSBCalibrateValue->setGeometry(QRect(10, 150, 91, 24));
        dSBCalibrateValue->setMaximum(999.99);
        labelCalibrateUnit = new QLabel(groupBox_2);
        labelCalibrateUnit->setObjectName(QStringLiteral("labelCalibrateUnit"));
        labelCalibrateUnit->setGeometry(QRect(107, 150, 31, 20));
        labelCalibrateUnit->setFont(font1);
        pBApplyCalibration = new QPushButton(groupBox_2);
        pBApplyCalibration->setObjectName(QStringLiteral("pBApplyCalibration"));
        pBApplyCalibration->setGeometry(QRect(115, 146, 61, 32));
        tabWidget->addTab(tabMeasurement, QString());
        tabAdvanced = new QWidget();
        tabAdvanced->setObjectName(QStringLiteral("tabAdvanced"));
        labelPaintPower = new QLabel(tabAdvanced);
        labelPaintPower->setObjectName(QStringLiteral("labelPaintPower"));
        labelPaintPower->setGeometry(QRect(349, 239, 391, 151));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Light, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Midlight, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Dark, brush2);
        palette1.setBrush(QPalette::Active, QPalette::Mid, brush3);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush);
        palette1.setBrush(QPalette::Active, QPalette::BrightText, brush1);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Active, QPalette::AlternateBase, brush1);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipBase, brush4);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Light, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Midlight, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Mid, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::BrightText, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush4);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Light, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Midlight, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::Mid, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::BrightText, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        labelPaintPower->setPalette(palette1);
        cos_phi = new QLabel(tabAdvanced);
        cos_phi->setObjectName(QStringLiteral("cos_phi"));
        cos_phi->setGeometry(QRect(260, 370, 61, 16));
        cos_phi->setFont(font1);
        label_73 = new QLabel(tabAdvanced);
        label_73->setObjectName(QStringLiteral("label_73"));
        label_73->setGeometry(QRect(220, 370, 31, 16));
        label_73->setFont(font1);
        graphAdvanced = new QCustomPlot(tabAdvanced);
        graphAdvanced->setObjectName(QStringLiteral("graphAdvanced"));
        graphAdvanced->setGeometry(QRect(350, 20, 401, 181));
        groupBox = new QGroupBox(tabAdvanced);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(10, 220, 191, 161));
        tabWidget->addTab(tabAdvanced, QString());
        tabScope = new QWidget();
        tabScope->setObjectName(QStringLiteral("tabScope"));
        customPlot = new QCustomPlot(tabScope);
        customPlot->setObjectName(QStringLiteral("customPlot"));
        customPlot->setGeometry(QRect(7, 10, 631, 391));
        lineEditRefreshTime = new QLineEdit(tabScope);
        lineEditRefreshTime->setObjectName(QStringLiteral("lineEditRefreshTime"));
        lineEditRefreshTime->setGeometry(QRect(644, 130, 61, 21));
        label_71 = new QLabel(tabScope);
        label_71->setObjectName(QStringLiteral("label_71"));
        label_71->setGeometry(QRect(640, 110, 81, 16));
        label_72 = new QLabel(tabScope);
        label_72->setObjectName(QStringLiteral("label_72"));
        label_72->setGeometry(QRect(740, 150, 21, 16));
        labelRefreshError = new QLabel(tabScope);
        labelRefreshError->setObjectName(QStringLiteral("labelRefreshError"));
        labelRefreshError->setGeometry(QRect(650, 150, 91, 16));
        comboBoxScope = new QComboBox(tabScope);
        comboBoxScope->setObjectName(QStringLiteral("comboBoxScope"));
        comboBoxScope->setGeometry(QRect(640, 10, 81, 26));
        radioButtonL1 = new QCheckBox(tabScope);
        radioButtonL1->setObjectName(QStringLiteral("radioButtonL1"));
        radioButtonL1->setGeometry(QRect(640, 40, 86, 20));
        radioButtonL2 = new QCheckBox(tabScope);
        radioButtonL2->setObjectName(QStringLiteral("radioButtonL2"));
        radioButtonL2->setGeometry(QRect(640, 60, 86, 20));
        radioButtonL3 = new QCheckBox(tabScope);
        radioButtonL3->setObjectName(QStringLiteral("radioButtonL3"));
        radioButtonL3->setGeometry(QRect(640, 80, 86, 20));
        scopeZoom = new QDial(tabScope);
        scopeZoom->setObjectName(QStringLiteral("scopeZoom"));
        scopeZoom->setGeometry(QRect(660, 320, 61, 71));
        scopeZoom->setMinimum(1);
        scopeZoom->setSingleStep(1);
        scopeZoom->setValue(10);
        label_74 = new QLabel(tabScope);
        label_74->setObjectName(QStringLiteral("label_74"));
        label_74->setGeometry(QRect(650, 310, 41, 16));
        scopeZoomLabel = new QLabel(tabScope);
        scopeZoomLabel->setObjectName(QStringLiteral("scopeZoomLabel"));
        scopeZoomLabel->setGeometry(QRect(690, 310, 31, 16));
        label_75 = new QLabel(tabScope);
        label_75->setObjectName(QStringLiteral("label_75"));
        label_75->setGeometry(QRect(710, 310, 16, 16));
        tabWidget->addTab(tabScope, QString());
        tabDatalogger = new QWidget();
        tabDatalogger->setObjectName(QStringLiteral("tabDatalogger"));
        tableWidgetData = new QTableWidget(tabDatalogger);
        tableWidgetData->setObjectName(QStringLiteral("tableWidgetData"));
        tableWidgetData->setGeometry(QRect(10, 30, 711, 361));
        pBAddDataloggerContent = new QPushButton(tabDatalogger);
        pBAddDataloggerContent->setObjectName(QStringLiteral("pBAddDataloggerContent"));
        pBAddDataloggerContent->setGeometry(QRect(150, 0, 71, 32));
        cBDataloggerList = new QComboBox(tabDatalogger);
        cBDataloggerList->setObjectName(QStringLiteral("cBDataloggerList"));
        cBDataloggerList->setGeometry(QRect(10, 2, 131, 26));
        pBSaveDataloggerToPath = new QPushButton(tabDatalogger);
        pBSaveDataloggerToPath->setObjectName(QStringLiteral("pBSaveDataloggerToPath"));
        pBSaveDataloggerToPath->setGeometry(QRect(630, 0, 91, 32));
        pBDeleteDataloggerContent = new QPushButton(tabDatalogger);
        pBDeleteDataloggerContent->setObjectName(QStringLiteral("pBDeleteDataloggerContent"));
        pBDeleteDataloggerContent->setGeometry(QRect(210, 0, 71, 32));
        rBEnableDatalogger = new QRadioButton(tabDatalogger);
        rBEnableDatalogger->setObjectName(QStringLiteral("rBEnableDatalogger"));
        rBEnableDatalogger->setGeometry(QRect(460, 5, 100, 20));
        sBDataloggerTime = new QSpinBox(tabDatalogger);
        sBDataloggerTime->setObjectName(QStringLiteral("sBDataloggerTime"));
        sBDataloggerTime->setGeometry(QRect(380, 4, 71, 24));
        sBDataloggerTime->setMaximum(100000);
        sBDataloggerTime->setValue(1000);
        tabWidget->addTab(tabDatalogger, QString());

        verticalLayout->addWidget(tabWidget);

        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 760, 22));
        menuCalls = new QMenu(menuBar);
        menuCalls->setObjectName(QStringLiteral("menuCalls"));
        menuTools = new QMenu(menuBar);
        menuTools->setObjectName(QStringLiteral("menuTools"));
        menuHelp = new QMenu(menuBar);
        menuHelp->setObjectName(QStringLiteral("menuHelp"));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);

        menuBar->addAction(menuCalls->menuAction());
        menuBar->addAction(menuTools->menuAction());
        menuBar->addAction(menuHelp->menuAction());
        menuCalls->addAction(actionConnect);
        menuCalls->addAction(actionDisconnect);
        menuCalls->addSeparator();
        menuCalls->addAction(actionQuit);
        menuTools->addAction(actionConfigure);
        menuTools->addAction(actionClear);
        menuHelp->addAction(actionAbout);
        mainToolBar->addAction(actionConnect);
        mainToolBar->addAction(actionDisconnect);
        mainToolBar->addAction(actionConfigure);
        mainToolBar->addAction(actionClear);

        retranslateUi(MainWindow);

        tabWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "PowerLAB", 0));
        actionAbout->setText(QApplication::translate("MainWindow", "PowerLab", 0));
#ifndef QT_NO_TOOLTIP
        actionAbout->setToolTip(QApplication::translate("MainWindow", "About program", 0));
#endif // QT_NO_TOOLTIP
        actionAbout->setShortcut(QApplication::translate("MainWindow", "Alt+A", 0));
        actionAboutQt->setText(QApplication::translate("MainWindow", "About Qt", 0));
        actionConnect->setText(QApplication::translate("MainWindow", "C&onnect", 0));
#ifndef QT_NO_TOOLTIP
        actionConnect->setToolTip(QApplication::translate("MainWindow", "Connect to serial port", 0));
#endif // QT_NO_TOOLTIP
        actionConnect->setShortcut(QApplication::translate("MainWindow", "Ctrl+O", 0));
        actionDisconnect->setText(QApplication::translate("MainWindow", "&Disconnect", 0));
#ifndef QT_NO_TOOLTIP
        actionDisconnect->setToolTip(QApplication::translate("MainWindow", "Disconnect from serial port", 0));
#endif // QT_NO_TOOLTIP
        actionDisconnect->setShortcut(QApplication::translate("MainWindow", "Ctrl+D", 0));
        actionConfigure->setText(QApplication::translate("MainWindow", "&Configure", 0));
#ifndef QT_NO_TOOLTIP
        actionConfigure->setToolTip(QApplication::translate("MainWindow", "Configure serial port", 0));
#endif // QT_NO_TOOLTIP
        actionConfigure->setShortcut(QApplication::translate("MainWindow", "Alt+C", 0));
        actionClear->setText(QApplication::translate("MainWindow", "C&lear", 0));
#ifndef QT_NO_TOOLTIP
        actionClear->setToolTip(QApplication::translate("MainWindow", "Clear data", 0));
#endif // QT_NO_TOOLTIP
        actionClear->setShortcut(QApplication::translate("MainWindow", "Alt+L", 0));
        actionQuit->setText(QApplication::translate("MainWindow", "&Quit", 0));
        actionQuit->setShortcut(QApplication::translate("MainWindow", "Ctrl+Q", 0));
        tabWidget->setTabText(tabWidget->indexOf(tabTerminal), QApplication::translate("MainWindow", "Terminal", 0));
        groupBoxPhase2_3->setTitle(QApplication::translate("MainWindow", "Total", 0));
        label_45->setText(QApplication::translate("MainWindow", "U:", 0));
        voltage_label_lt->setText(QApplication::translate("MainWindow", "000.00", 0));
        label_46->setText(QApplication::translate("MainWindow", "V", 0));
        label_47->setText(QApplication::translate("MainWindow", "A", 0));
        label_48->setText(QApplication::translate("MainWindow", "I:", 0));
        current_label_lt->setText(QApplication::translate("MainWindow", "000.00", 0));
        label_49->setText(QApplication::translate("MainWindow", "A", 0));
        label_50->setText(QApplication::translate("MainWindow", "P:", 0));
        power_label_lt->setText(QApplication::translate("MainWindow", "000.00", 0));
        label_51->setText(QApplication::translate("MainWindow", "VA", 0));
        label_52->setText(QApplication::translate("MainWindow", "S:", 0));
        apparent_label_lt->setText(QApplication::translate("MainWindow", "000.00", 0));
        label_53->setText(QApplication::translate("MainWindow", "var", 0));
        label_54->setText(QApplication::translate("MainWindow", "Q:", 0));
        reactive_label_lt->setText(QApplication::translate("MainWindow", "000.00", 0));
        powerfactor_label_lt->setText(QApplication::translate("MainWindow", "000.00", 0));
        label_57->setText(QApplication::translate("MainWindow", "\302\260C", 0));
        label_58->setText(QApplication::translate("MainWindow", "Hz", 0));
        temperature_label->setText(QApplication::translate("MainWindow", "00.00", 0));
        label_56->setText(QApplication::translate("MainWindow", "T:", 0));
        label_59->setText(QApplication::translate("MainWindow", "F:", 0));
        frequency_label->setText(QApplication::translate("MainWindow", "00.00", 0));
        label_20->setText(QApplication::translate("MainWindow", "\316\273:", 0));
        groupBoxPhase2->setTitle(QApplication::translate("MainWindow", "Phase 2", 0));
        label_23->setText(QApplication::translate("MainWindow", "U:", 0));
        voltage_label_l2->setText(QApplication::translate("MainWindow", "000.0000", 0));
        label_24->setText(QApplication::translate("MainWindow", "V", 0));
        label_25->setText(QApplication::translate("MainWindow", "A", 0));
        label_26->setText(QApplication::translate("MainWindow", "I:", 0));
        current_label_l2->setText(QApplication::translate("MainWindow", "000.0000", 0));
        label_27->setText(QApplication::translate("MainWindow", "W", 0));
        label_28->setText(QApplication::translate("MainWindow", "P:", 0));
        power_label_l2->setText(QApplication::translate("MainWindow", "000.0000", 0));
        label_29->setText(QApplication::translate("MainWindow", "VA", 0));
        label_30->setText(QApplication::translate("MainWindow", "S:", 0));
        apparent_label_l2->setText(QApplication::translate("MainWindow", "000.0000", 0));
        label_31->setText(QApplication::translate("MainWindow", "var", 0));
        label_32->setText(QApplication::translate("MainWindow", "Q:", 0));
        reactive_label_l2->setText(QApplication::translate("MainWindow", "000.0000", 0));
        powerfactor_label_l2->setText(QApplication::translate("MainWindow", "000.0000", 0));
        energyCounterp_label_l2->setText(QApplication::translate("MainWindow", "000.00", 0));
        label_16->setText(QApplication::translate("MainWindow", "E:", 0));
        label_15->setText(QApplication::translate("MainWindow", "\316\273:", 0));
        label_17->setText(QApplication::translate("MainWindow", "\317\206:", 0));
        cosinusPhi_label_l2->setText(QApplication::translate("MainWindow", "000.0", 0));
        label_33->setText(QApplication::translate("MainWindow", "\342\210\240", 0));
        groupBoxPhase2_2->setTitle(QApplication::translate("MainWindow", "Phase 3", 0));
        label_34->setText(QApplication::translate("MainWindow", "U:", 0));
        voltage_label_l3->setText(QApplication::translate("MainWindow", "000.0000", 0));
        label_35->setText(QApplication::translate("MainWindow", "V", 0));
        label_36->setText(QApplication::translate("MainWindow", "A", 0));
        label_37->setText(QApplication::translate("MainWindow", "I:", 0));
        current_label_l3->setText(QApplication::translate("MainWindow", "000.0000", 0));
        label_38->setText(QApplication::translate("MainWindow", "W", 0));
        label_39->setText(QApplication::translate("MainWindow", "P:", 0));
        power_label_l3->setText(QApplication::translate("MainWindow", "000.0000", 0));
        label_40->setText(QApplication::translate("MainWindow", "VA", 0));
        label_41->setText(QApplication::translate("MainWindow", "S:", 0));
        apparent_label_l3->setText(QApplication::translate("MainWindow", "000.0000", 0));
        label_42->setText(QApplication::translate("MainWindow", "var", 0));
        label_43->setText(QApplication::translate("MainWindow", "Q:", 0));
        reactive_label_l3->setText(QApplication::translate("MainWindow", "000.0000", 0));
        powerfactor_label_l3->setText(QApplication::translate("MainWindow", "000.0000", 0));
        energyCounterp_label_l3->setText(QApplication::translate("MainWindow", "000.00", 0));
        label_18->setText(QApplication::translate("MainWindow", "E:", 0));
        label_19->setText(QApplication::translate("MainWindow", "\316\273:", 0));
        label_21->setText(QApplication::translate("MainWindow", "\317\206:", 0));
        cosinusPhi_label_l3->setText(QApplication::translate("MainWindow", "000.0", 0));
        label_44->setText(QApplication::translate("MainWindow", "\342\210\240", 0));
        groupBoxPhase1->setTitle(QApplication::translate("MainWindow", "Phase 1", 0));
        label->setText(QApplication::translate("MainWindow", "U:", 0));
        voltage_label_l1->setText(QApplication::translate("MainWindow", "000.0000", 0));
        label_2->setText(QApplication::translate("MainWindow", "V", 0));
        label_3->setText(QApplication::translate("MainWindow", "A", 0));
        label_4->setText(QApplication::translate("MainWindow", "I:", 0));
        current_label_l1->setText(QApplication::translate("MainWindow", "000.0000", 0));
        label_5->setText(QApplication::translate("MainWindow", "W", 0));
        label_6->setText(QApplication::translate("MainWindow", "P:", 0));
        power_label_l1->setText(QApplication::translate("MainWindow", "000.0000", 0));
        label_7->setText(QApplication::translate("MainWindow", "VA", 0));
        label_8->setText(QApplication::translate("MainWindow", "S:", 0));
        apparent_label_l1->setText(QApplication::translate("MainWindow", "000.0000", 0));
        label_9->setText(QApplication::translate("MainWindow", "var", 0));
        label_10->setText(QApplication::translate("MainWindow", "Q:", 0));
        reactive_label_l1->setText(QApplication::translate("MainWindow", "000.0000", 0));
        powerfactor_label_l1->setText(QApplication::translate("MainWindow", "000.0000", 0));
        label_12->setText(QApplication::translate("MainWindow", "\316\273:", 0));
        energyCounterp_label_l1->setText(QApplication::translate("MainWindow", "000.0000", 0));
        label_13->setText(QApplication::translate("MainWindow", "E:", 0));
        label_14->setText(QApplication::translate("MainWindow", "\317\206:", 0));
        cosinusPhi_label_l1->setText(QApplication::translate("MainWindow", "000.0", 0));
        label_22->setText(QApplication::translate("MainWindow", "\342\210\240", 0));
        label_11->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-style:italic;\">\302\256 Nils Minor 2016</span></p></body></html>", 0));
        groupBox_2->setTitle(QApplication::translate("MainWindow", "Function", 0));
        pushButton->setText(QApplication::translate("MainWindow", "Clear Energycounter", 0));
        startSimmulation->setText(QApplication::translate("MainWindow", "Simmulation Panel", 0));
        bB_save_flash->setText(QApplication::translate("MainWindow", "save", 0));
        cbUseSimmulatedData->setText(QApplication::translate("MainWindow", "Use simmulated Data", 0));
        comboBox->clear();
        comboBox->insertItems(0, QStringList()
         << QApplication::translate("MainWindow", "RMS", 0)
         << QApplication::translate("MainWindow", "Instantaneous", 0)
        );
        label_60->setText(QApplication::translate("MainWindow", "Measurement", 0));
        label_63->setText(QApplication::translate("MainWindow", "Sample values", 0));
#ifndef QT_NO_WHATSTHIS
        spinBoxAverage->setWhatsThis(QApplication::translate("MainWindow", "<html><head/><body><p>This value represents the amount of measurements used to <span style=\" font-family:'Arial';\">average</span> the data input.</p></body></html>", 0));
#endif // QT_NO_WHATSTHIS
        label_62->setText(QApplication::translate("MainWindow", "ms / 10 ", 0));
        period_label->setText(QApplication::translate("MainWindow", "000.00", 0));
        label_61->setText(QApplication::translate("MainWindow", "Period:", 0));
        bB_clear_flash->setText(QApplication::translate("MainWindow", "clear", 0));
        label_64->setText(QApplication::translate("MainWindow", "Flash", 0));
        pB_CallibrateOffsetCurrent->setText(QApplication::translate("MainWindow", "Callib. Offset Current", 0));
        cBCalibrationSelection->clear();
        cBCalibrationSelection->insertItems(0, QStringList()
         << QApplication::translate("MainWindow", "Calibration Target", 0)
         << QApplication::translate("MainWindow", "V1 RMS", 0)
         << QApplication::translate("MainWindow", "V2 RMS", 0)
         << QApplication::translate("MainWindow", "V3 RMS", 0)
         << QApplication::translate("MainWindow", "I1 RMS", 0)
         << QApplication::translate("MainWindow", "I2 RMS", 0)
         << QApplication::translate("MainWindow", "I3 RMS", 0)
        );
        label_65->setText(QApplication::translate("MainWindow", "Calib.:", 0));
        labelCalibrateUnit->setText(QApplication::translate("MainWindow", "?", 0));
        pBApplyCalibration->setText(QApplication::translate("MainWindow", "Apply", 0));
        tabWidget->setTabText(tabWidget->indexOf(tabMeasurement), QApplication::translate("MainWindow", "Measurement", 0));
        labelPaintPower->setText(QString());
        cos_phi->setText(QApplication::translate("MainWindow", "000.00", 0));
        label_73->setText(QApplication::translate("MainWindow", "Phi:", 0));
        groupBox->setTitle(QApplication::translate("MainWindow", "Values", 0));
        tabWidget->setTabText(tabWidget->indexOf(tabAdvanced), QApplication::translate("MainWindow", "Advanced", 0));
        lineEditRefreshTime->setText(QApplication::translate("MainWindow", "20", 0));
        label_71->setText(QApplication::translate("MainWindow", "Refreshtime", 0));
        label_72->setText(QApplication::translate("MainWindow", "ms", 0));
        labelRefreshError->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; font-style:italic; color:#ff0000;\">error</span></p><p><span style=\" font-size:9pt; font-weight:600; font-style:italic;\"><br/></span></p><p><span style=\" font-size:9pt; font-weight:600; font-style:italic;\"><br/></span></p></body></html>", 0));
        comboBoxScope->clear();
        comboBoxScope->insertItems(0, QStringList()
         << QApplication::translate("MainWindow", "Voltage RMS", 0)
         << QApplication::translate("MainWindow", "Current RMS", 0)
         << QApplication::translate("MainWindow", "Active Power", 0)
         << QApplication::translate("MainWindow", "Reactive Power", 0)
         << QApplication::translate("MainWindow", "Apparent Power", 0)
         << QApplication::translate("MainWindow", "Energy Counter", 0)
        );
        radioButtonL1->setText(QApplication::translate("MainWindow", "Phase 1", 0));
        radioButtonL2->setText(QApplication::translate("MainWindow", "Phase 2", 0));
        radioButtonL3->setText(QApplication::translate("MainWindow", "Phase 3", 0));
        label_74->setText(QApplication::translate("MainWindow", "Zoom", 0));
        scopeZoomLabel->setText(QApplication::translate("MainWindow", "0", 0));
        label_75->setText(QApplication::translate("MainWindow", "%", 0));
        tabWidget->setTabText(tabWidget->indexOf(tabScope), QApplication::translate("MainWindow", "Scope", 0));
        pBAddDataloggerContent->setText(QApplication::translate("MainWindow", "Add", 0));
        pBSaveDataloggerToPath->setText(QApplication::translate("MainWindow", "Save to ...", 0));
        pBDeleteDataloggerContent->setText(QApplication::translate("MainWindow", "Delete", 0));
        rBEnableDatalogger->setText(QApplication::translate("MainWindow", "enable", 0));
        tabWidget->setTabText(tabWidget->indexOf(tabDatalogger), QApplication::translate("MainWindow", "Datalogger", 0));
        menuCalls->setTitle(QApplication::translate("MainWindow", "Calls", 0));
        menuTools->setTitle(QApplication::translate("MainWindow", "Tools", 0));
        menuHelp->setTitle(QApplication::translate("MainWindow", "Help", 0));
        mainToolBar->setWindowTitle(QApplication::translate("MainWindow", "PowerLab", 0));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
